language: php

php: [5.4, 5.5, 5.6, hhvm]

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --dev

script: bin/codecept run --debug

branches:
  only:
    - master